# Generated by Django 4.2.11 on 2024-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption_1', models.TextField()),
                ('caption_2', models.TextField()),
                ('caption_3', models.TextField()),
                ('caption_4', models.TextField()),
                ('caption_5', models.TextField()),
            ],
        ),
    ]
