# Generated by Django 5.1.2 on 2024-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_remove_image_image_url_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
